use_frameworks!
inhibit_all_warnings!

target 'SimpleChatIOS' do
  platform :ios, '11.3'
  pod 'sReto/AllModules', :path => '../../'
end

target 'SimpleChatMac' do
  platform :osx, '10.13.4'
  pod 'sReto/AllModules', :path => '../../'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.1'
        end
    end
end
