use_frameworks!
inhibit_all_warnings!

target :sRetoIOS do
  platform :ios, '11.3'
  pod 'CocoaAsyncSocket', '7.6.3'
  pod 'SocketRocket', '0.5.1'
  
  target :sRetoTests do
  end
    
end

target :sRetoMac do
  platform :osx, '10.13.4'
  pod 'CocoaAsyncSocket', '7.6.3'
  pod 'SocketRocket', '0.5.1'
end
